### ISSUE TITLE
List computers under licence

### ISSUE THREAD

**Issue by tekmans** [pulse-project/pulse#18]
Add the possibility to view the computer list (or create a group) to view the computers that have this package.

![selection_139](https://cloud.githubusercontent.com/assets/1766087/19637779/0c56cb24-99d1-11e6-982e-4dc689b5dcdb.png)

**Comment by spointu** [comment]
tested and working

**Comment by tekmans** [comment]
something strange when query is empty
![image](https://cloud.githubusercontent.com/assets/1766087/22465875/123f9ada-e7be-11e6-839a-99f22fd7b76a.png)

Result

![image](https://cloud.githubusercontent.com/assets/1766087/22465821/e114a4fa-e7bd-11e6-89ca-c5fdbda5e021.png)

**Comment by tekmans** [comment]
This feature is working properly but "Associating an inventory" to a package must be debug
https://github.com/pulse-project/pulse/issues/92
