### ISSUE TITLE
Display hostname instead of ip

### ISSUE THREAD

**Issue by tekmans** [pulse-project/pulse#25]
To easily understand which relay server is, change ip by hostname.

Is present when a package is in the sync phase.

![selection_006](https://cloud.githubusercontent.com/assets/1766087/20130939/7a6df9ee-a65a-11e6-9526-42dce9077622.png)

**Comment by spointu** [comment]
This only needs to be configured in package-server.ini.local
Use FQDN instead of IP in package_mirror_target
