### ISSUE TITLE
Add "domain junction" options in sysprep 

### ISSUE THREAD

**Issue by tekmans** [pulse-project/pulse#31]
Add Microsoft-Windows-UnattendedJoin to specialize .
In Credentials setup the username and password of a Domain administrator. The user
must have the rights to join a computer to the domain. Specify also the domain name.
In JoinDomain specify the domain to join.
By default the computer will be added in the default ou =Computer branch. You can specify
another OU to use in the MachineObjectOU setting. Specify the full LDAP dn (ex : ou=my
computers, dc=domain.local )

**Comment by botheis** [comment]
Closed by commit e58061ec595523e41699e73bcf568d03973d9fb7

**Comment by spointu** [comment]
Tested and working. The AD domain needs however to be resolvable via DNS
