### ISSUE TITLE
Imaging and backup server and dropdown list

### ISSUE THREAD

**Issue by tekmans** [pulse-project/pulse#33]
By default for those two servers (backup, imaging) on MMC, shows "no server for this entity".
The selected state of the dropdown list is uuid0.

![selection_085](https://cloud.githubusercontent.com/assets/1766087/20922339/16f0238e-bba8-11e6-9663-10a3b75f64e1.png)

It could be better to select by default the right uuid as uuid1

**Comment by tekmans** [comment]
Needs also in imaging group creation

![image](https://cloud.githubusercontent.com/assets/1766087/21173744/824581ba-c1d9-11e6-8365-c7bd26d51bd7.png)

**Comment by spointu** [comment]
Tested and working
