### ISSUE TITLE
pagination link are not easily clickable

### ISSUE THREAD

**Issue by tekmans** [pulse-project/pulse#5]
The pagination must just over the computer list

![selection_135](https://cloud.githubusercontent.com/assets/1766087/13074868/996c8b92-d4a7-11e5-8991-5662eb1e4ee6.png)

**Comment by tekmans** [comment]
To reproduce change the number of computer in /etc/mmc/mmc.ini
; Number of items to display in lists
maxperpage = 2

**Comment by neoclust** [comment]
fixed by 7b2db112071220abb1acc3eb4941cf963f1c08f7

**Comment by spointu** [comment]
Tested and working
