### ISSUE TITLE
Inventory OS name is splitted in two

### ISSUE THREAD

**Issue by tekmans** [pulse-project/pulse#84]
Since 0.91 the field OS Name is only the manufacturer, the version is an another filed.
Please add this field in computer list and inventory detail view.

**Comment by neoclust** [comment]
Fixed in new install-pulse

**Comment by neoclust** [comment]
fixed in https://github.com/pulse-project/tools/commit/0da33ef398964d609de3f438e22421a45657a357

**Comment by neoclust** [comment]
and typo fixed here : https://github.com/pulse-project/tools/commit/6b471c0c446207561ef3c299c32d2564f1e47b23
